export const WORKOUTS = {
  A: {
    name: 'Workout A — Push / Core / Shoulders',
    rounds: '3 rounds · rest 60–90 sec between rounds',
    warmup: [
      { name: 'Arm Circles',   detail: '10 forward, 10 backward' },
      { name: 'Hip Circles',   detail: '10 each direction' },
      { name: 'Jumping Jacks', detail: '30 seconds' },
      { name: 'Cat-Cow',       detail: '8 reps' },
    ],
    circuit: [
      { name: 'Push-Ups',         detail: '12–15 reps',           cue: 'Chest to floor. If struggling, modify to knees — full range beats partial reps.' },
      { name: 'Pike Push-Ups',    detail: '10–12 reps',           cue: 'Hips high, inverted V position, head moves toward the floor. This is the shoulder press of bodyweight.' },
      { name: 'Tricep Dips',      detail: '12–15 reps',           cue: 'Use a chair or couch edge. Elbows track straight back, not flaring out.' },
      { name: 'Plank Hold',       detail: '30–45 seconds',        cue: 'Dead-straight line from head to heel. Don\'t let hips sag or pike. Breathe steadily.',        timed: true, targetSec: 40 },
      { name: 'Mountain Climbers',detail: '20 reps (10 each leg)',cue: 'Hands under shoulders, keep hips level — don\'t bounce them.' },
      { name: 'Hollow Body Hold', detail: '20–30 seconds',        cue: 'Lower back pressed hard into the floor, arms overhead. This one will humble you.',               timed: true, targetSec: 25 },
    ],
    cooldown: [
      { name: 'Child\'s Pose',          detail: '30 seconds' },
      { name: 'Doorway Chest Stretch',  detail: '30 seconds each side' },
      { name: 'Seated Forward Fold',    detail: '45 seconds' },
      { name: 'Thread the Needle',      detail: '30 seconds each side' },
    ],
  },
  B: {
    name: 'Workout B — Legs / Glutes / Posterior Chain',
    rounds: '3 rounds · rest 60–90 sec between rounds',
    warmup: [
      { name: 'Leg Swings',                detail: '10 forward/back, 10 side-to-side each leg' },
      { name: 'Slow Bodyweight Squats',    detail: '5 reps, 3 seconds down, controlled' },
      { name: 'Glute Bridge Activation',   detail: '10 slow reps, squeeze at top' },
      { name: 'Ankle Circles',             detail: '10 each direction' },
    ],
    circuit: [
      { name: 'Bodyweight Squats',  detail: '15–20 reps',        cue: 'Feet shoulder-width, chest up, knees track over toes. Go to parallel or below.' },
      { name: 'Reverse Lunges',     detail: '10 each leg',       cue: 'Step back, back knee hovers one inch from the floor. Front shin stays vertical.' },
      { name: 'Glute Bridges',      detail: '15 reps + 5s hold', cue: 'Drive through heels. Squeeze hard at the top. Key exercise for posterior chain.' },
      { name: 'Superman Hold',      detail: '10 reps, 2s hold',  cue: 'Arms forward, lift chest and legs simultaneously. Lower back and glutes doing the work.' },
      { name: 'Wall Sit',           detail: '30–45 seconds',     cue: 'Thighs parallel to floor, back flat against wall. No sliding.',                              timed: true, targetSec: 40 },
      { name: 'Calf Raises',        detail: '20 reps',           cue: 'Slow and controlled, full range. Heels drop below platform edge if possible.' },
    ],
    cooldown: [
      { name: 'Pigeon Pose',                 detail: '60 seconds each side — don\'t skip this' },
      { name: 'Standing Hamstring Stretch',  detail: '30 seconds each leg' },
      { name: 'Low Lunge Hip Flexor Stretch',detail: '45 seconds each side' },
      { name: 'Calf + Achilles Stretch',     detail: '30 seconds each leg' },
    ],
  },
  stability: {
    name: 'Stability Training — Balance / Core / Unilateral',
    rounds: '3 rounds · rest 60 sec between rounds',
    warmup: [
      { name: 'Single-Leg Balance',   detail: '30 seconds each leg, eyes open' },
      { name: 'Hip Circles',          detail: '10 each direction' },
      { name: 'Cat-Cow',              detail: '8 reps' },
      { name: 'Dead Bug (warm-up)',   detail: '5 reps each side, slow' },
    ],
    circuit: [
      { name: 'Dead Bug',                   detail: '8 reps each side',    cue: 'Lower back glued to floor. Opposite arm + leg extend slowly. Do not let the back arch.' },
      { name: 'Bird Dog',                   detail: '10 reps each side',   cue: 'From all-fours — extend opposite arm and leg, pause 2 seconds. Spine stays flat. Do not rotate hips.' },
      { name: 'Side Plank',                 detail: '30–40 sec each side', cue: 'Feet stacked or staggered. Hips up and square. Don\'t let the bottom hip sag.',          timed: true, targetSec: 35 },
      { name: 'Single-Leg Glute Bridge',    detail: '12 reps each leg',   cue: 'One leg extended straight. Drive through the heel. Hips stay level.' },
      { name: 'Y-T-W (lying prone)',        detail: '8 reps each position',cue: 'Lying face down, lift arms to Y, then T, then W. Squeezes mid-back and rear delts. Light and controlled.' },
      { name: 'Pallof Press Hold',          detail: '20–30 sec each side', cue: 'No band? Half-kneel, reach both arms straight forward and hold. Resist rotation — trunk stays square.', timed: true, targetSec: 25 },
    ],
    cooldown: [
      { name: 'Pigeon Pose',     detail: '45 seconds each side' },
      { name: 'Thread the Needle',detail: '30 seconds each side' },
      { name: 'Child\'s Pose',   detail: '30 seconds' },
      { name: 'Supine Twist',    detail: '30 seconds each side' },
    ],
  },
  bike: {
    name: 'Bike Ride',
    rounds: '20–30 min stationary',
    warmup: [{ name: 'Easy pace', detail: '3–5 min to warm up' }],
    circuit: [{ name: 'Steady ride', detail: '20–30 min', cue: 'Comfortable effort. Not a rest day, not a suffer-fest.' }],
    cooldown: [{ name: 'Easy spin', detail: '3–5 min to cool down' }],
  },
  rest: null,
}
